export const AUTHENTICATION = 'AUTHENTICATION';
export const FETCH_ACCOUNT_INFORMATION = 'FETCH_ACCOUNT_INFORMATION';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

export const FETCH_ACCOUNT_LIST = 'FETCH_ACCOUNT_LIST';
export const FETCH_PROFILE = 'FETCH_PROFILE';
export const ADD_ACCOUNT = 'ADD_ACCOUNT';
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
export const EDIT_ACCOUNT = 'EDIT_ACCOUNT';